"use client";

import React, { useState } from "react";
import { logRevenueAction } from "@/actions/revenue.actions";
import { Loader2, DollarSign, Plus, CheckCircle, AlertCircle, TrendingUp, HelpCircle, Wrench, Fuel } from "lucide-react";

interface VehicleSummary {
  id: string;
  name: string;
  registrationNumber: string;
}

interface CostliestVehicle {
  id: string;
  name: string;
  registrationNumber: string;
  fuelCost: number;
  maintCost: number;
  operationalCost: number;
  tollExpense: number;
  otherExpense: number;
}

interface MonthlyRevenue {
  month: string; // YYYY-MM
  revenue: number;
}

interface RoiRecord {
  id: string;
  name: string;
  registrationNumber: string;
  acquisitionCost: number;
  totalRevenue: number;
  fuelCost: number;
  maintCost: number;
  operationalCost: number;
  tollExpense: number;
  otherExpense: number;
  netProfit: number;
  roi: number;
}

interface FinancialDashboardProps {
  vehiclesList: VehicleSummary[];
  topCostliest: CostliestVehicle[];
  monthlyRevenue: MonthlyRevenue[];
  roiReport: RoiRecord[];
  currencySymbol?: string;
}

export function FinancialDashboard({
  vehiclesList,
  topCostliest,
  monthlyRevenue,
  roiReport,
  currencySymbol = "$",
}: FinancialDashboardProps) {
  // Revenue Logging form state
  const [vehicleId, setVehicleId] = useState("");
  const [monthStr, setMonthStr] = useState("");
  const [amount, setAmount] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleLogRevenue = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setError(null);
    setSuccess(false);

    try {
      const res = await logRevenueAction(vehicleId, monthStr, Number(amount));
      if (res.success) {
        setSuccess(true);
        setAmount("");
        setTimeout(() => {
          setSuccess(false);
          window.location.reload(); // Reload to refresh datasets
        }, 1500);
      } else {
        setError(res.error || "Failed to log revenue.");
      }
    } catch (err) {
      console.error(err);
      setError("An unexpected error occurred.");
    } finally {
      setIsSubmitting(false);
    }
  };

  // SVG Bar Chart Calculations
  const chartHeight = 240;
  const paddingX = 40;
  const paddingY = 30;
  const width = 500;
  const maxRev = monthlyRevenue.length > 0 ? Math.max(...monthlyRevenue.map((r) => r.revenue), 1000) * 1.15 : 1000;

  return (
    <div className="space-y-8">
      {/* 2 Column Top Panel */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        {/* Left Side: Log Form + Costliest list */}
        <div className="lg:col-span-5 space-y-6">
          {/* Revenue Logging Form */}
          <div className="bg-white border border-gray-200 rounded-card p-5 shadow-small space-y-4">
            <div>
              <h3 className="text-sm font-extrabold text-gray-900 uppercase tracking-wider flex items-center gap-1.5">
                <DollarSign className="w-4 h-4 text-emerald-500" />
                Log Monthly Revenue
              </h3>
              <p className="text-[11px] text-gray-400">Record total earnings generated by individual vehicle assets per month</p>
            </div>

            {error && (
              <div className="p-3 bg-red-50 border border-red-150 text-red-700 text-xs rounded-input font-medium flex items-center gap-1.5">
                <AlertCircle className="w-4 h-4 text-red-650 shrink-0" />
                {error}
              </div>
            )}

            {success && (
              <div className="p-3 bg-emerald-50 border border-emerald-150 text-emerald-700 text-xs rounded-input font-medium flex items-center gap-1.5">
                <CheckCircle className="w-4 h-4 text-emerald-600 shrink-0" />
                Monthly revenue entry logged successfully.
              </div>
            )}

            <form onSubmit={handleLogRevenue} className="space-y-4 text-left">
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-gray-500 uppercase tracking-wider">
                  Assign Vehicle Asset
                </label>
                <select
                  required
                  value={vehicleId}
                  onChange={(e) => setVehicleId(e.target.value)}
                  className="w-full h-9 px-2 bg-white border border-gray-300 text-gray-900 text-xs rounded-input focus:outline-none focus:border-primary-500 select-arrow"
                >
                  <option value="">-- Choose fleet vehicle --</option>
                  {vehiclesList.map((v) => (
                    <option key={v.id} value={v.id}>
                      {v.registrationNumber} — {v.name}
                    </option>
                  ))}
                </select>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-500 uppercase tracking-wider">
                    Select Month
                  </label>
                  <input
                    type="month"
                    required
                    value={monthStr}
                    onChange={(e) => setMonthStr(e.target.value)}
                    className="w-full h-9 px-3 bg-white border border-gray-300 text-gray-900 text-xs rounded-input focus:outline-none focus:border-primary-500"
                  />
                </div>

                <div className="space-y-1">
                  <label className="text-[10px] font-bold text-gray-500 uppercase tracking-wider">
                    Revenue Earned ({currencySymbol})
                  </label>
                  <input
                    type="number"
                    required
                    min={0}
                    step="any"
                    value={amount}
                    onChange={(e) => setAmount(e.target.value)}
                    className="w-full h-9 px-3 bg-white border border-gray-300 text-gray-900 text-xs rounded-input focus:outline-none focus:border-primary-500"
                    placeholder="3500"
                  />
                </div>
              </div>

              <button
                type="submit"
                disabled={isSubmitting}
                className="w-full h-10 bg-primary-600 hover:bg-primary-750 text-white text-xs font-bold rounded-button transition-colors flex items-center justify-center gap-1.5 shadow-small"
              >
                {isSubmitting ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Plus className="w-4 h-4" />
                )}
                Save Revenue Entry
              </button>
            </form>
          </div>

          {/* Top Costliest Vehicles */}
          <div className="bg-white border border-gray-200 rounded-card p-5 shadow-small space-y-4">
            <div>
              <h3 className="text-sm font-extrabold text-gray-900 uppercase tracking-wider">
                Top Costliest Vehicles
              </h3>
              <p className="text-[11px] text-gray-400">Ranked by total operational cost (Fuel + Maintenance only)</p>
            </div>

            <div className="space-y-3">
              {topCostliest.length === 0 ? (
                <p className="text-xs text-gray-400 text-center py-4">No operating cost records logged.</p>
              ) : (
                topCostliest.map((item, idx) => (
                  <div key={item.id} className="flex items-center justify-between border-b border-gray-100 pb-2 text-xs">
                    <div className="space-y-0.5">
                      <div className="font-bold text-gray-900">
                        {idx + 1}. {item.registrationNumber}
                      </div>
                      <div className="text-[10px] text-gray-400">{item.name}</div>
                      <div className="text-[9px] text-gray-500 flex gap-2">
                        <span className="flex items-center gap-0.5"><Fuel className="w-2.5 h-2.5" />{currencySymbol}{item.fuelCost.toLocaleString()}</span>
                        <span className="flex items-center gap-0.5"><Wrench className="w-2.5 h-2.5" />{currencySymbol}{item.maintCost.toLocaleString()}</span>
                      </div>
                    </div>
                    <div className="text-right">
                      <span className="font-extrabold text-red-650">{currencySymbol}{item.operationalCost.toLocaleString()}</span>
                      <span className="block text-[8px] text-gray-400 uppercase tracking-wider">Total Op. Cost</span>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>

        {/* Right Side: Monthly Revenue Chart */}
        <div className="lg:col-span-7 bg-white border border-gray-200 rounded-card p-5 shadow-small space-y-4 h-full flex flex-col justify-between">
          <div>
            <h3 className="text-sm font-extrabold text-gray-900 uppercase tracking-wider flex items-center gap-1.5">
              <TrendingUp className="w-4 h-4 text-primary-500" />
              Monthly Revenue Aggregates
            </h3>
            <p className="text-[11px] text-gray-400">Chronological summary of verified organization profits per month</p>
          </div>

          <div className="flex-1 min-h-[220px] flex items-center justify-center pt-4">
            {monthlyRevenue.length === 0 ? (
              <p className="text-xs text-gray-400">No monthly revenue entries to display.</p>
            ) : (
              <svg width="100%" height={chartHeight} viewBox={`0 0 ${width} ${chartHeight}`} className="overflow-visible font-sans text-[10px]">
                {/* Horizontal grid lines */}
                {[0, 0.25, 0.5, 0.75, 1].map((ratio) => {
                  const y = paddingY + (1 - ratio) * (chartHeight - paddingY * 2);
                  const val = Math.round(ratio * maxRev);
                  return (
                    <g key={ratio}>
                      <line x1={paddingX} y1={y} x2={width - paddingX} y2={y} stroke="#f1f5f9" strokeWidth={1} />
                      <text x={paddingX - 8} y={y + 3} textAnchor="end" fill="#94a3b8" className="font-mono">
                        {currencySymbol}{val >= 1000 ? `${(val / 1000).toFixed(1)}k` : val}
                      </text>
                    </g>
                  );
                })}

                {/* Vertical Bars */}
                {monthlyRevenue.map((item, idx) => {
                  const chartW = width - paddingX * 2;
                  const stepX = monthlyRevenue.length > 1 ? chartW / (monthlyRevenue.length - 1) : chartW;
                  const x = paddingX + idx * stepX;
                  const barH = (item.revenue / maxRev) * (chartHeight - paddingY * 2);
                  const y = chartHeight - paddingY - barH;

                  return (
                    <g key={item.month}>
                      <rect
                        x={x - 10}
                        y={y}
                        width={20}
                        height={barH}
                        fill="#6366f1"
                        rx={3}
                        className="hover:fill-indigo-600 transition-colors cursor-pointer"
                      />
                      {/* Bar Value Tooltip Text */}
                      <text x={x} y={y - 6} textAnchor="middle" fill="#4338ca" className="font-bold font-mono">
                        {currencySymbol}{Math.round(item.revenue)}
                      </text>
                      {/* X Label */}
                      <text x={x} y={chartHeight - paddingY + 15} textAnchor="middle" fill="#64748b" className="font-semibold">
                        {item.month}
                      </text>
                    </g>
                  );
                })}
              </svg>
            )}
          </div>
        </div>
      </div>

      {/* ROI Report Table */}
      <div className="bg-white border border-gray-200 rounded-card p-6 shadow-small space-y-4">
        <div>
          <h3 className="text-sm font-extrabold text-gray-900 uppercase tracking-wider flex items-center gap-1.5">
            Fleet Asset ROI report
          </h3>
          <p className="text-[11px] text-gray-400">
            Formula: <code>ROI = (Total Revenue - Operational Cost) / Acquisition Cost</code> (Operational Cost = Fuel + Maintenance only)
          </p>
        </div>

        <div className="overflow-x-auto border border-gray-150 rounded-lg">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="border-b border-gray-200 bg-gray-50/60 text-[9px] font-bold text-gray-500 uppercase tracking-wider">
                <th className="px-4 py-3">Vehicle Plate</th>
                <th className="px-4 py-3">Model Name</th>
                <th className="px-4 py-3 text-right">Acquisition</th>
                <th className="px-4 py-3 text-right">Total Revenue</th>
                <th className="px-4 py-3 text-right">Fuel Cost</th>
                <th className="px-4 py-3 text-right">Maintenance</th>
                <th className="px-4 py-3 text-right bg-red-50/30 text-red-800 font-bold border-x border-gray-250">Op. Cost</th>
                <th className="px-4 py-3 text-right text-gray-400">Tolls</th>
                <th className="px-4 py-3 text-right text-gray-400">Other Exp.</th>
                <th className="px-4 py-3 text-right bg-emerald-50/30 text-emerald-800 font-bold border-x border-gray-250">Net Profit</th>
                <th className="px-4 py-3 text-right bg-primary-50/30 text-primary-800 font-extrabold border-l border-gray-250">ROI (%)</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-150">
              {roiReport.length === 0 ? (
                <tr>
                  <td colSpan={11} className="px-4 py-8 text-center text-gray-400 font-semibold">
                    No fleet metrics records found.
                  </td>
                </tr>
              ) : (
                roiReport.map((v) => (
                  <tr key={v.id} className="hover:bg-gray-50/20 transition-colors">
                    <td className="px-4 py-3 font-mono font-bold text-gray-700">
                      {v.registrationNumber}
                    </td>
                    <td className="px-4 py-3 font-medium text-gray-800">{v.name}</td>
                    <td className="px-4 py-3 text-right font-semibold text-gray-700">
                      {currencySymbol}{v.acquisitionCost.toLocaleString()}
                    </td>
                    <td className="px-4 py-3 text-right font-semibold text-emerald-700">
                      {currencySymbol}{v.totalRevenue.toLocaleString()}
                    </td>
                    <td className="px-4 py-3 text-right text-gray-600">
                      {currencySymbol}{v.fuelCost.toLocaleString()}
                    </td>
                    <td className="px-4 py-3 text-right text-gray-600">
                      {currencySymbol}{v.maintCost.toLocaleString()}
                    </td>
                    <td className="px-4 py-3 text-right bg-red-50/10 font-extrabold text-red-650 border-x border-gray-150">
                      {currencySymbol}{v.operationalCost.toLocaleString()}
                    </td>
                    <td className="px-4 py-3 text-right text-gray-450 font-medium">
                      {currencySymbol}{v.tollExpense.toLocaleString()}
                    </td>
                    <td className="px-4 py-3 text-right text-gray-450 font-medium">
                      {currencySymbol}{v.otherExpense.toLocaleString()}
                    </td>
                    <td className="px-4 py-3 text-right bg-emerald-50/10 font-extrabold text-emerald-700 border-x border-gray-150">
                      {currencySymbol}{v.netProfit.toLocaleString()}
                    </td>
                    <td className={`px-4 py-3 text-right font-extrabold border-l border-gray-150 bg-primary-50/10 ${v.roi >= 0 ? "text-primary-600" : "text-rose-600"}`}>
                      {v.roi}%
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
